### ISSUE TITLE
Support Azure TTS

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#1]
- Along side iOS built in voices we want to use an online system. There are lots but we might as well start with one that is well documented. Microsoft Azure (and Ace Centre already pay $$ for Azure so why not..) 
- We need to:
-  In settings you can pick a voice - grouped by Language.  - Choose your voice - Provide a voice picker from this system or IOS (and the in the future other voice systems)
-   Now in the speak screen we want a way of “caching” the audio. So it should by default cache the text. Any changes it will need to rerun the caching system. This means storing a Mp4 or other file format in the background. This will allow for offline access. Of course only needs to be done for this online voice but could I guess work for system voices too
- Would need building into https://github.com/AceCentre/TextAloud/blob/main/TextAloud/Models/SpeechSynthesizer.swift

Here’s a starter to get started. It will need a cocoapod adding from Microsoft - and you’ll need our key. See details below. 

1. https://learn.microsoft.com/en-gb/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=linux%2Cubuntu%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cios%2Cpypi&pivots=programming-language-swift
2. https://learn.microsoft.com/en-gb/azure/cognitive-services/speech-service/get-started-text-to-speech?tabs=windows%2Cterminal&pivots=programming-language-swift

**Comment by tapokoff** [comment]
First you need to close #6 and #7 . After that, implement the ability to select a speech synthesizer and connect Azure TTS. Also, before all this, you need to redo the application settings storage, this will be partially solved in #7
