### ISSUE TITLE
Buggy reading

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#10]
"I have had a play with ~TextAloud but it seems quite buggy in that sometimes it refuses to read any text no matter which button I press and when I set it off reading in the middle of a long piece of text it did read it but it scrolled up and down the4 document very fast as it was reading in a peculiar way."

**Comment by tapokoff** [comment]
Its seems like a bug, I need the text with which customer have troubles to reproduce this bug and I will try to find solution
