### ISSUE TITLE
Combine speech sources list

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/TextAloud#20]
I think most users will be confused if we ask them to pick which 'speech service', or even if they do understand they are more likely to want to be able to sort by 'All French Voices' than they are by 'All Apple Voices'. 

I think it would be nicer if all the voices were combined into the single picker, although maybe a label at the end of the source might be helpful.

From a user perspective, you probably aren't overly fussed about the source of your voice, just the language and the voice.

**Comment by willwade** [comment]
closing this for now - as kinda done.
