### ISSUE TITLE
Can't edit text

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#25]
Go to change where the cursor is in text. You enter the first letter then it jumps to the end https://user-images.githubusercontent.com/229352/221008189-8fff6560-aa20-4b81-b06f-42094d9af04d.MOV

**Comment by gavinhenderson** [comment]
@willwade This still seems like a problem on the latest version

https://user-images.githubusercontent.com/1359202/221813394-32f0edc7-6c94-4235-a41e-c9941fcd94c0.MOV

**Comment by taananas** [comment]
Hello, Gavin! I've some problems with highlights the text

**Comment by taananas** [comment]
![IMAGE 2023-02-28 18:48:58](https://user-images.githubusercontent.com/116089887/221905393-6d0a4fed-87f2-4c69-a6c4-703c6c8a691c.jpg)

**Comment by taananas** [comment]
now it works like this: every character update updates the ui text view, it redraws the text with attributes and sends the cursor to the end

I'll try to think how to fix it, but it's very difficult, really

**Comment by gavinhenderson** [comment]
@taananas Interesting! I looked into it a little more and it seems to only happen sometimes. After clicking the clear button it lets me edit freely but if I edit directly after playing a word it keeps jumping to the end.

In the attached video you can see it working sometimes but also sometimes not. Do you have any idea what might be causing this?https://user-images.githubusercontent.com/1359202/221905612-9e7c4065-7cd1-483b-99f8-14a02b9c48bc.MOV

Could we fix it by only updating the the UI view when the user clicks save? We could just disable all highlighting whilst the user is in edit mode?

It's doesnt really if the editor forgets what was highlighted once you enter edit mode.

**Comment by taananas** [comment]
'Could we fix it by only updating the the UI view when the user clicks save? We could just disable all highlighting whilst the user is in edit mode?' I did it

**Comment by gavinhenderson** [comment]
@taananas Thanks! Ill close this issue now :)

**Comment by taananas** [comment]
Cool, I got it)
