### ISSUE TITLE
Voice selector via settings UI is confusing

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/TextAloud#26]
https://user-images.githubusercontent.com/1359202/221014513-c1173001-6e6d-4a8a-86c2-48b4b93ffbb2.MOV

**Comment by willwade** [comment]
That looks v .. different .. on iPad.

**Comment by gavinhenderson** [comment]
@willwade The voice selector that you access via the switcher in the bottom left is what I would expect, but when you go through settings it seems to wrap it in an extra view

**Comment by willwade** [comment]
take a look now. Think this is fixed. 

 NB: a couple of things to note:
- The home screen has a quick switcher. Its way of speaking in one language/voice and swapping to another. One tap to a different language. But note it wont change Left to right -> Right to left. Only changing the system keyboard will do that. I don't think its a big problem as I understand the TTS deals with it fine. 
- In the main settings dialogue you choose any number of voices that then appear in the quick switcher. Note to delete a selected voice it should not be the active voice and you swipe left on it.

**Comment by willwade** [comment]
going to close this for now. Just reopen @gavinhenderson  if you think its still in existence
