### ISSUE TITLE
Play button - Usability issue

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#27]
I think I need to clarify the play button. Its a bit confusing..

- If you tap on a word - and then press play it will read the word/sentence or paragraph. Thats fine
- But if nothing is selected it reads the entire page. 

I think what it should do is

- if a string element tapped on - it should read it as it currently does
- And then find the next element and stop. (Or - we should provide a Next and Previous button to allow the user to step through each item)

- If nothing selected read the first word/sentence/paragraph. Then move to the next and stop.
- Pressing play again will read the next one.

https://user-images.githubusercontent.com/229352/221215398-a0ada3ca-1d50-483c-882b-492c457d2ff0.mp4

**Comment by taananas** [comment]
https://user-images.githubusercontent.com/116089887/221533607-f59d800c-787a-48a7-bc07-730d88da7043.MP4

https://user-images.githubusercontent.com/116089887/221533737-4bc5fb18-c543-4608-b9d3-a5a2ecce0cb0.MP4

**Comment by willwade** [comment]
Amazing. Im tempted to go with the second option as its then less interaction from the user. It could be confusing if you want to replay a string but I think this is the right interaction for the use case
