### ISSUE TITLE
Dealing with being offline

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#29]
There are some issues if your voice is an azure voice and your device goes offline. RIght now, it caches the whole audio file if you play the whole thing. But It won't cache sentences. Its too difficult to do this and I don't think we need to if we can support ssml (#2  ) But if you go offline and haven't cached the thing - or just want to play a word/sentence/para it just won't. You don't get any alert or anything. Should we? Maybe a small banner that temporarily sits at the top that tells you that is offline. But only if you swap to a azure voice.

**Comment by gavinhenderson** [comment]
> Maybe a small banner that temporarily sits at the top that tells you that is offline. But only if you swap to a azure voice. 

Sounds like a good plan to me!

**Comment by taananas** [comment]
> There are some issues if your voice is an azure voice and your device goes offline. RIght now, it caches the whole audio file if you play the whole thing. But It won't cache sentences. Its too difficult to do this and I don't think we need to if we can support ssml (#2 ) But if you go offline and haven't cached the thing - or just want to play a word/sentence/para it just won't. You don't get any alert or anything. Should we? Maybe a small banner that temporarily sits at the top that tells you that is offline. But only if you swap to a azure voice.

what do you mean by 'offline mode'? blocking?

**Comment by willwade** [comment]
If the device doesn’t have access to the internet. Eg. Flight mode

**Comment by taananas** [comment]
> 

aha, okay, I got it! I'll do it tomorrow)

**Comment by taananas** [comment]
Hello, Will and Gavin! I've created a new option, what do you think about it?

https://user-images.githubusercontent.com/116089887/222401004-706d6f5d-ad96-4291-8088-6dd5313362d5.MP4
