### ISSUE TITLE
Sentence bounds.

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#34]
![image](https://user-images.githubusercontent.com/229352/222079514-e8992c39-ae06-4ec3-9bab-f0463de32c0c.png)

So this says 

TextAloud is a different kind of AAC app. It’s about playing text  rather than writing text. bore da. Sut wyt ti?

why is ". bore da." Seen as the previous sentence - not as a stand-alone sentence?

**Comment by willwade** [comment]
Ah it's because bore da. Not Bore da.

**Comment by taananas** [comment]
I also connected a new sentence determinant of words and paragraphs yesterday. Try to write sentences with capital letters. If it starts with small ones, then it does not determine exactly where the new offer is.

**Comment by willwade** [comment]
Just commenting this for reference to @gavinhenderson  range comment re: #47
