### ISSUE TITLE
Check word / document formats it supports

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#36]
From a end user 

"The first word doc I did I couldn't add it in got error message "Failed to upload, try again" several times.
- have a screenshot - can't work out where in the app to send this feedback to you the developers!
Made a 2nd word doc, that worked ok.
Tried the 1st word doc again and it did upload but it did line breaks where I hadn't had them. Weird!
This might be because I'd originally done the text for this one in Notes and when I couldn't upload from Notes into the app I copied and pasted it into a Word doc.
Be good to give instruction on whether you can use Notes or if you have to use Word?"

**Comment by taananas** [comment]
there is a problem here, yes...

notes files are supported, to open them in the application, you first need to save notes file on your device, and then open it in your application. 

and with docx files, the situation is different. Sometimes the SNDocx library cannot process their information the first time and errors occur, I can't do anything about it, unfortunately, there is a problem in SNDocx.

**Comment by taananas** [comment]
app supports rtf, pdf, docx, txt files. I checked everything and I've them open
