### ISSUE TITLE
Twice in a row.

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#37]
Need to investigate this. 

"Can't repeat the same sentence twice in a row - need to click elsewhere - either on to another sentence - which you won't really want if you're not wanting to say that - or you can click on an empty row if you've got one of these in your document. But you can't click on the bottom of the doc in the white space."

**Comment by willwade** [comment]
I think i know what's happening. We changed play so that it moves onto the next sentence / word / para. The problem is the old sentence is highlighted after playing. Not the new one.

**Comment by taananas** [comment]
could you send me a video with this problem?
