### ISSUE TITLE
Rate slider

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#40]
Can we change rate of speaking for online and offline? I know we had a rate changer for offline but that's gone now.

I'm fine if we can only change rate for offline - or we just reflect what the system voice rate is set to. Online will be fixed when we support ssml.

**Comment by taananas** [comment]
'rate' I removed because it's only for offline mode, azure doesn't support it in tts mode

> Can we change rate of speaking for online and offline? I know we had a rate changer for offline but that's gone now.
> 
> I'm fine if we can only change rate for offline - or we just reflect what the system voice rate is set to. Online will be fixed when we support ssml.

**Comment by taananas** [comment]
> I think this is related. Look at the video below. It starts off really fast in rate. Then slows down. https://user-images.githubusercontent.com/229352/223041434-b8fcb07f-3825-4a05-9c52-b324de466699.MOV

yeah I set up the speed in the general settings

**Comment by taananas** [comment]
but this is only for apple and only offline

how will it do in terms of design?

**Comment by willwade** [comment]
So Offline (Apple). Set your rate in Settings -> Accessibility -> Spoken Content

Online - will we wait till we support SSML. That sound ok?
