### ISSUE TITLE
Sending text from notes

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#41]
I can't easily get text from notes app. If we made it accessible via the share sheet to receive text would that solve it?

**Comment by taananas** [comment]
you can export from the notes application only if you saved the file locally and then opened it in your app, via 'sheet' share and 'save on phone'

**Comment by taananas** [comment]
maybe I can add the app to the 'action sheet' later

**Comment by willwade** [comment]
This is setup.. But - its not working on testflight...

We think it should look like this in the Signing of both the extension and app:

![Uploading Screenshot 2023-03-07 at 20.16.34.jpeg…]()

But its failing for me. 

![Uploading Screenshot 2023-03-07 at 17.35.18.png…]()

@gavinhenderson   - this might be a "fun" one for you.

**Comment by gavinhenderson** [comment]
Hmmm I'll have a look, at least it gives you nice descriptive errors!

**Comment by willwade** [comment]
FYI - when you upload you find you get an error that you need to change NSExtensionActivationSupportsText in the extension to a boolean (right click on the value type and change the type). Its a integer in the repo

<img width="538" alt="Screenshot 2023-03-07 at 16 55 40" src="https://user-images.githubusercontent.com/229352/223573738-ecbc8a74-facf-47c0-b451-97fca3e014ec.png">

**Comment by gavinhenderson** [comment]
This now works on the newest testflight build
