### ISSUE TITLE
Highlighting inconsistencies

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#46]
Sometimes it highlights yellow. Sometimes not. https://user-images.githubusercontent.com/229352/223218423-98be346d-ec66-4a1b-938b-18e05a7508e2.MOV

https://share.icloud.com/photos/013wS4q5ZZbiQlUXr_tI3rXrQ

**Comment by gavinhenderson** [comment]
It also seemed to skip a sentance when it dropped the highlights

**Comment by taananas** [comment]
> https://user-images.githubusercontent.com/229352/223218423-98be346d-ec66-4a1b-938b-18e05a7508e2.MOV

the video doesn't work

**Comment by taananas** [comment]
> Sometimes it highlights yellow. Sometimes not. https://user-images.githubusercontent.com/229352/223218423-98be346d-ec66-4a1b-938b-18e05a7508e2.MOV
> 
> https://share.icloud.com/photos/013wS4q5ZZbiQlUXr_tI3rXrQ

the video doesn't work

**Comment by taananas** [comment]
https://user-images.githubusercontent.com/116089887/223422161-20bb91a4-0817-4680-b38d-345fd0c6c3f0.mov

**Comment by willwade** [comment]
aha - have you fixed this @taananas ?

**Comment by taananas** [comment]
everything will work fine if you don't mix the text with the language of the sounds, which is not there

> aha - have you fixed this @taananas ?

**Comment by willwade** [comment]
I see - so related to #47
